spring.application.name=eventflow

spring.datasource.url=jdbc:postgresql://localhost:5432/eventdb
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=V2xNQzJvY3VJQ2lLQ1ZQNW9jQ2Z4U3M3RzNnRjNQQmN0Qk9xQ0JqN2l4Yw==
jwt.expiration=86400000